name: IPTV Advanced Auto Update

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests aiohttp

      - name: Decrypt and Run
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          CORE_PASS: ${{ secrets.CORE_PASS }} # পাসওয়ার্ড পাস করা
        run: python decrypt.py
