name: Auto Update Playlist
on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 📦 Checkout code
        uses: actions/checkout@v4

      - name: 🐍 Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip' # এটি requirements.txt এর এরর কমাবে

      - name: 📥 Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 📡 Fetch Tokens
        run: python fetch_playlist.py

      - name: 🚀 Commit & Push
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add playlist.m3u
          git commit -m "Auto Update: $(date)" || exit 0
          git push
